### ISSUE TITLE
一回 deviseを試してみる

### ISSUE THREAD

**Issue by miyzawa** [zakkana/message_app#6]
rails new devise -d mysql
で
このサイト試してみる
https://qiita.com/cigalecigales/items/73d7bd7ec59a001ccd74

**Comment by zakkana** [comment]
最終的な参考サイト
https://qiita.com/cigalecigales/items/f4274088f20832252374#1-%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E5%BE%8C%E3%81%AE%E3%83%9A%E3%83%BC%E3%82%B8%E3%82%92%E5%A4%89%E6%9B%B4%E3%81%99%E3%82%8B
https://qiita.com/shizuma/items/c8c2e71af8c1dcf3d1c2
Fixes #45

**Comment by zakkana** [comment]
close #6
